### ISSUE TITLE
Submitting match predictions doesn't redirect anywhere

### ISSUE THREAD

**Issue by luca652** [StuF83/futball_fantasy#41]

**Comment by StuF83** [comment]
I think it should redirect to the competition show page

**Comment by luca652** [comment]
Sounds good. Is it ok if assign this to myself?

**Comment by StuF83** [comment]
Awsome mate yes please

**Comment by StuF83** [comment]
Yep, you're right. How about for the interim we link to the competition index page? Then, if we want we could build out a user profile page which could list the competitions they are in, their current predictions, their standings etc... and have the submit button just drop them back there?

**Comment by luca652** [comment]
great mate, just pushed it and created pull request.
